#!/bin/bash

alias dev="cd ~/Development"
alias glol="git log --oneline"
alias gl10="git log --oneline -n 10"
alias gd="git diff"
alias gds="git diff --staged"
alias gdn="git diff --name-only"

alias sl="ls"
alias ls="ls -G"
alias irb="pry"
alias be="bundle exec"

# make `g` behave like `git status` with no args, or `git` with args
g () {
  if [ $# -eq 0 ]
  then
    git status
  else
    git "$@"
  fi
}

d () {
  if [ $# -eq 0 ]
  then
    docker container ls
  else
    docker "$@"
  fi
}

__git_complete g _git
