#!/usr/bin/bash

source /etc/default/waydroid-launcher

# Kill any previous remnants
pkexec /usr/libexec/waydroid-container-stop

# Launch Cage & Waydroid
pkexec /usr/libexec/waydroid-container-start

waydroid show-full-ui &

/home/aarron/.local/bin/clear-waydroid-desktop-entries

