#!/usr/bin/bash

source /etc/default/waydroid-launcher

# Kill any previous remnants
if [ "$(systemctl is-active waydroid-container.service)" == 'active' ]; then
	pkexec /usr/libexec/waydroid-container-stop
fi

# Launch Cage & Waydroid
pkexec /usr/libexec/waydroid-container-start

waydroid show-full-ui &

/home/aarron/.local/bin/clear-waydroid-desktop-entries

