#!/bin/bash

alias dev="cd ~/Development"
alias glol="git log --oneline"
alias gl10="git log --oneline -n 10"
alias gd="git diff"
alias gds="git diff --staged"
alias gdn="git diff --name-only"
alias qrcode="flameshot gui --raw | zbarimg --raw - | xclip -in -selection clipboard"
alias ocr="flameshot gui --raw | \
  tesseract stdin stdout | \
  xclip -in -selection clipboard"
alias mangaocr="flameshot gui --path /tmp/mangaocr/ocr_tmp | manga_ocr --read_from=\"/tmp/mangaocr/\" -w clipboard | rm /tmp/mangaocr/ocr_tmp.png"
alias chcon_bin="sudo chcon -u system_u -r object_r --type=bin_t "
alias lapce="flatpak run dev.lapce.lapce "


alias sl="ls"
alias ls="ls -G"
alias irb="pry"
alias be="bundle exec"

alias toggle-touch="bash ~/.dotfiles/scripts/toggle-touchscreen.sh"

# make `g` behave like `git status` with no args, or `git` with args
g () {
  if [ $# -eq 0 ]
  then
    git status
  else
    git "$@"
  fi
}

# make `gco` behave like git checkout
gco () {
  git checkout "$@"
}

d () {
  if [ $# -eq 0 ]
  then
    docker container ls
  else
    docker "$@"
  fi
}

__git_complete g _git
__git_complete gco _git_checkout
